### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 2)

### ISSUE THREAD

**Issue by scutfrank** [drivsaf/MFAN#1]
Traceback (most recent call last):
  File "D:/1.Study/PycharmProjects/MFAN-main/graph_part/weibo_threemodal.py", line 591, in <module>
    train_and_test(model)
  File "D:/1.Study/PycharmProjects/MFAN-main/graph_part/weibo_threemodal.py", line 569, in train_and_test
    nn.fit(X_train_tid, X_train, y_train,
  File "D:/1.Study/PycharmProjects/MFAN-main/graph_part/weibo_threemodal.py", line 335, in fit
    self.evaluate(X_dev_tid, X_dev, y_dev)
  File "D:/1.Study/PycharmProjects/MFAN-main/graph_part/weibo_threemodal.py", line 338, in evaluate
    y_pred = self.predict(X_dev_tid, X_dev)
  File "D:/1.Study/PycharmProjects/MFAN-main/graph_part/weibo_threemodal.py", line 363, in predict
    logits, **grad**, dist = self.forward(batch_x_tid, batch_x_text)

After remove **grad** ,the code run successfully ,want to know my correction is right?

**Comment by 2ezInCode** [comment]
maybe right  because grad and dist are not used
应该是对的，grad和dist都没有用到 amaz 我继续跑跑
